language: python

git:
  depth: 5

python:
  - 2.7
  - 3.6

env:
  - TOX_ENV=odoo10-unit
    ODOO_URI=https://github.com/merchise-autrement/odoo.git

  - TOX_ENV=odoo11-unit
    ODOO_URI=https://github.com/merchise-autrement/odoo.git

matrix:
  exclude:
    - env: TOX_ENV=odoo10-unit
      python: 3.6

    - env: TOX_ENV=odoo11-unit
      python: 2.7

install: pip install tox
script: tox -e system-$TOX_ENV
