language: python
dist: xenial
git:
  depth: 5

python:
  - 2.7
  - 3.6
  - 3.7

env:
  - TOX_ENV=odoo10-unit
  - TOX_ENV=odoo11-unit
  - TOX_ENV=odoo12-unit

matrix:
  exclude:
    - env: TOX_ENV=odoo10-unit
      python: 3.6

    - env: TOX_ENV=odoo11-unit
      python: 2.7

    - env: TOX_ENV=odoo12-unit
      python: 2.7

install: pip install tox
script:
    - export ODOO_URI=https://github.com/merchise-autrement/odoo.git
    - tox -e system-$TOX_ENV
